### ISSUE TITLE
Disappearing photos completely missing

### ISSUE THREAD

**Issue by highda** [mautrix/meta#72]
I saw no template here, so please forgive me for this freeform bug report. Anyway.
The issue exists with Instagram messages, specifically pictures sent using the camera button in the official app (those with "View once", "Allow replay" or "Keep in chat" option).

These pictures are completely ignored by the bridge (I am a Beeper user and I hope Beeper uses the latest version of this bridge)-

I am not sure how [this app](https://github.com/noook/igdm-cli ) accomplishes such a feat, only thing I know is that it has no problem displaying this attachment type. Might be worth a check, unless it's running a headless browser in the background, then idk.

**Comment by tulir** [comment]
Beeper issues should be reported via the built-in report bug mechanism, not here

Anyway, it's a known bug in instagram itself. If you log into the instagram web app, open the chat, then receive a photo sent with the camera button, you'll notice it doesn't show up at all until you reload the page, and even after that it just shows a "no longer available" placeholder (even for keep in chat images). The bug is weirdly region-specific, doesn't seem to affect users in the US at least. The bridge will work immediately once instagram fixes the bug on their servers.
